---
- name: 'Download wordpress'
  get_url: 
    url: 'https://br.wordpress.org/latest-pt_BR.tar.gz'
    dest: '/tmp/latest-pt_BR.tar.gz'

- name: 'Descompactando o wordpress'
  unarchive: 
    src: '/tmp/latest-pt_BR.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- copy:
    src: "{{wordpress_dir}}/wp-config-sample.php"
    dest: "{{wordpress_dir}}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'wp-config'
  replace:
    path: "{{wordpress_dir}}/wp-config.php"
    regexp: '{{item.regex}}'
    replace: '{{item.value}}'
  with_items:
    - { regex: 'nome_do_banco_de_dados_aqui', value: "{{database_name}}"  }
    - { regex: 'nome_de_usuario_aqui', value: "{{database_user}}"  }
    - { regex: 'senha_aqui', value: "{{database_password}}"  }
    - { regex: 'localhost', value: "{{database_ip}}"  }
  become: yes

- name: 'Apache conf'
  template:
    src: 'templates/000-default.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify: restart_apache